### ISSUE TITLE
Add support for jakarta package namespace

### ISSUE THREAD

**Issue by sbillet** [threeten-jaxb/threeten-jaxb#19]
Thank you for providing this useful library! We are using it together with `org.eclipse.persistence.moxy` for mashalling XML documents with date and time attributes.

Starting from 3.0.0 Moxy uses the `jakarta.xml.bind` package namespace instead of `javax.xml.bind`. As `threeten-jaxb` relies on the old namespace, it is not compatible with moxy >= 3.0.0. I imagine other Java EE/Jakarta libraries have the some problem.

If you could give a hint or add support for the new namespace (possibly in an alternative version), it would be much appreciated.

**Comment by mkroening** [comment]
I'm glad, this is useful.

I just published [`v2.0.0`](https://github.com/threeten-jaxb/threeten-jaxb/releases/tag/v2.0.0) which uses `jakarta` instead of `javax`. Does that work for you?

**Comment by sbillet** [comment]
Thank you for the swift update!
I tried it, but it turned out that other dependencies in our application are not ready for the Jaxb Jakarta switch yet, namely [Spring Boot](https://github.com/spring-projects/spring-boot/issues/27020).
I will revisit this when Spring Boot 3 gets released.
